[package]
name = "badapple-raylib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raylib = "3.7"
rodio = "0.16.0"
winapi = {version = "0.3", features = ["wincon", "winuser"]}
